version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    container_name: car_rental_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d:ro

  backend:
    build:
      context: .
      dockerfile: ./apps/car-rental-backend/Dockerfile
      target: development
    command: npm run serve:car-rental-backend
    container_name: car_rental_backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
    volumes:
      - .:/app
      - /app/node_modules
  
  frontend:
    build:
      context: .
      dockerfile: ./apps/car-rental/Dockerfile
      target: development
    command: npm run serve:car-rental -- --host 0.0.0.0
    container_name: car_rental_frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules

networks:
  default:
    name: car_rental_network
    driver: bridge