SET NAMES utf8mb4;

USE car_rental;

CREATE TABLE vehicle_brands (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (name)
);

ALTER TABLE vehicle_brands
CONVERT TO CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;