SET NAMES utf8mb4;

USE car_rental;

CREATE TABLE addresses (
    id INT AUTO_INCREMENT NOT NULL,
    street VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    administrativeArea VARCHAR(255) NOT NULL,
    postalCode VARCHAR(255) NOT NULL,
    country VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

ALTER TABLE addresses
CONVERT TO CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;