name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      # Run linting
      - name: Run lint
        run: npx nx affected --target=lint --parallel --no-cloud

      # Run tests
      - name: Run tests
        run: npx nx affected --target=test --parallel --no-cloud

      # Build all projects
      - name: Build all projects
        run: npx nx affected --target=build --parallel --no-cloud